#!/bin/sh
# 引入 OpenWrt 系统自带的 LED 功能函数库，里面包含了配置 LED 的专用命令
. /lib/functions/leds.sh
# 引入 UCI 默认配置函数库，用于在系统首次启动时写入基础配置文件
. /lib/functions/uci-defaults.sh

# 调用 board_name 命令，获取当前路由器具体的硬件型号标识（例如 bt,r320-emmc）
board=$(board_name)

# 开始更新板级配置（准备向 /etc/config/system 写入 LED 规则）
board_config_update

# 根据获取到的设备型号（$board），进入不同的配置分支
case $board in
# 如果设备型号包含 "Airpi"
*Airpi*)
	# 设置 2.4G WiFi 灯，绑定网卡 rax0，状态为 link（链路连接）
	ucidef_set_led_netdev "wlan2g" "WLAN2G" "airpi:2g" "rax0" "link"
        # 设置 5G WiFi 灯，绑定网卡 ra0，状态为 link
        ucidef_set_led_netdev "wlan5g" "WLAN5G" "airpi:5g" "ra0" "link"
	;;
# 针对 abt,asr3000 这款设备
abt,asr3000)
	# 设置 WAN 口灯，绑定 eth1 网卡
	ucidef_set_led_netdev "wan" "WAN" "green:wan" "eth1"
	# 设置 2.4G WiFi 灯，绑定 phy0-ap0 接口
	ucidef_set_led_netdev "wlan2g" "WLAN2G" "green:wlan-2ghz" "phy0-ap0"
	# 设置 5G WiFi 灯，绑定 phy1-ap0 接口
	ucidef_set_led_netdev "wlan5g" "WLAN5G" "green:wlan-5ghz" "phy1-ap0"
	;;
# 针对你关注的 BT-R320 (eMMC版) 设备
bt,r320-emmc)
	# 设置 2.4G WiFi 灯：内部名"wlan2g"，显示名"WLAN2G"，对应系统LED名"green:wlan-2ghz"，绑定无线接口"ra0"
	ucidef_set_led_netdev "wlan2g" "WLAN2G" "green:wlan-2ghz" "ra0"
	# 设置 5G WiFi 灯：内部名"wlan5g"，显示名"WLAN5G"，对应系统LED名"green:wlan-5ghz"，绑定无线接口"rax0"
	ucidef_set_led_netdev "wlan5g" "WLAN5G" "green:wlan-5ghz" "rax0"
	;;
# 针对华硕 rt-ax52 设备
asus,rt-ax52)
	# 设置蓝色的 WAN 口灯，绑定 wan 接口，状态为 link tx rx（连接、发送、接收数据时都会亮）
	ucidef_set_led_netdev "wan" "wan" "blue:wan" "wan" "link tx rx"
	;;
# 针对香蕉派 bpi-r3-mini 设备
bananapi,bpi-r3-mini)
	# 设置 LAN1 口灯，支持 2500M/1000M 速率连接及数据传输指示
	ucidef_set_led_netdev "lan1" "LAN" "mdio-bus:0e:green:lan" "eth0" "link_2500 link_1000 tx rx"
	ucidef_set_led_netdev "lan2" "LAN" "mdio-bus:0e:yellow:lan" "eth0" "link_2500 link_100 tx rx"
	ucidef_set_led_netdev "wan1" "WAN" "mdio-bus:0f:green:wan" "eth1" "link_2500 link_1000 tx rx"
	ucidef_set_led_netdev "wan2" "WAN" "mdio-bus:0f:yellow:wan" "eth1" "link_2500 link_100 tx rx"
	ucidef_set_led_netdev "wlan2g" "WLAN2G" "blue:wlan-1" "phy0-ap0"
	ucidef_set_led_netdev "wlan5g" "WLAN5G" "blue:wlan-2" "phy1-ap0"
	;;
# 针对香蕉派 bpi-r4 及其 POE 版本
bananapi,bpi-r4|\
bananapi,bpi-r4-poe)
	ucidef_set_led_netdev "wan" "wan" "mt7530-0:00:green:lan" "wan" "link tx rx"
	ucidef_set_led_netdev "lan1" "lan1" "mt7530-0:01:green:lan" "lan1" "link tx rx"
	ucidef_set_led_netdev "lan2" "lan2" "mt7530-0:02:green:lan" "lan2" "link tx rx"
	ucidef_set_led_netdev "lan3" "lan3" "mt7530-0:03:green:lan" "lan3" "link tx rx"
	;;
# 针对 confiaBits mt7981 开发板
confiabits,mt7981)
	ucidef_set_led_netdev "lan1" "lan1" "blue:lan-1" "lan1" "link tx rx"
	ucidef_set_led_netdev "lan2" "lan2" "blue:lan-2" "lan2" "link tx rx"
	ucidef_set_led_netdev "lan3" "lan3" "blue:lan-3" "lan3" "link tx rx"
	ucidef_set_led_netdev "wan" "wan" "blue:wan" "wan" "link tx rx"
	;;
# 针对 cudy re3000-v1 或 wavlink wl-wn573hx3
cudy,re3000-v1|\
wavlink,wl-wn573hx3)
	ucidef_set_led_netdev "lan" "lan" "green:lan" "eth0" "link tx rx"
	;;
# 针对 cudy wr3000-v1
cudy,wr3000-v1)
	ucidef_set_led_netdev "wan" "wan" "blue:wan" "wan"
	;;
# 针对 glinet (广和通) x3000 / xe3000 系列
glinet,gl-x3000|\
glinet,gl-xe3000)
	ucidef_set_led_default "power" "POWER" "green:power" "1" # 设置电源灯默认为常亮(1)
	ucidef_set_led_netdev "wan" "WAN" "green:wan" "eth0"
	# 以下是 5G 蜂窝网络的信号强度指示灯（wwan0 代表无线广域网接口）
	ucidef_set_led_netdev "5g_1" "5G_1" "green:5g:led1" "wwan0"
	ucidef_set_led_netdev "5g_2" "5G_2" "green:5g:led2" "wwan0"
	ucidef_set_led_netdev "5g_3" "5G_3" "green:5g:led3" "wwan0"
	ucidef_set_led_netdev "5g_4" "5G_4" "green:5g:led4" "wwan0"
	ucidef_set_led_netdev "wlan2g" "WLAN2G" "green:wifi2g" "phy0-ap0"
	ucidef_set_led_netdev "wlan5g" "WLAN5G" "green:wifi5g" "phy1-ap0"
	;;
# 针对 huasifei wh3000-emmc
huasifei,wh3000-emmc)
	ucidef_set_led_netdev "wan" "WAN" "red:wan" "eth1"
	;;
# 针对 imou lc-hx3001 或 nokia ea0326gmp
imou,lc-hx3001|\
nokia,ea0326gmp)
	ucidef_set_led_netdev "wan" "WAN" "green:wan" "eth1" "link"
	ucidef_set_led_netdev "lan" "LAN" "green:lan" "br-lan" "link" # 绑定到 br-lan 网桥，代表所有局域网口
	ucidef_set_led_netdev "wlan" "WLAN" "green:wlan" "phy1-ap0" "link"
	;;
# 针对 livinet zr-3020 及其 ubootmod 版本
livinet,zr-3020|\
livinet,zr-3020-ubootmod)
	ucidef_set_led_netdev "internet" "INTERNET" "blue:internet" "wan"
	ucidef_set_led_netdev "wlan2g" "WLAN2G" "blue:wlan2g" "phy0-ap0"
	ucidef_set_led_netdev "wlan5g" "WLAN5G" "blue:wlan5g" "phy1-ap0"
	;;
# 针对联发科官方的 7981r128 参考设计板
mediatek,7981r128)
	ucidef_set_led_netdev "lan" "LAN" "LAN" "lan2"
	ucidef_set_led_netdev "sfp" "SFP" "SFP" "eth1" "link"
	ucidef_set_led_netdev "wifi5g" "WIFI5G" "WIFI5G" "rax0" "tx rx" # 仅在数据收发(tx rx)时闪烁
	ucidef_set_led_netdev "wifi2g" "WIFI2G" "WIFI2G" "ra0" "tx rx"
	;;
# 针对 mercusys mr80x-v3
mercusys,mr80x-v3)
	ucidef_set_led_netdev "lan1" "lan-1" "green:lan-1" "lan1" "link tx rx"
	ucidef_set_led_netdev "lan2" "lan-2" "green:lan-2" "lan2" "link tx rx"
	ucidef_set_led_netdev "lan3" "lan-3" "green:lan-3" "lan3" "link tx rx"
	ucidef_set_led_netdev "wan" "wan" "green:wan" "wan" "link tx rx"
	;;
# 针对 mercusys mr90x-v1 及其 ubi 版本
mercusys,mr90x-v1|\
mercusys,mr90x-v1-ubi)
	ucidef_set_led_netdev "lan-0" "lan-0" "green:lan-0" "lan0" "link tx rx"
	ucidef_set_led_netdev "lan-1" "lan-1" "green:lan-1" "lan1" "link tx rx"
	ucidef_set_led_netdev "lan-2" "lan-2" "green:lan-2" "lan2" "link tx rx"
	ucidef_set_led_netdev "wan" "wan" "green:wan" "eth1" "link tx rx"
	;;
# 针对 netcore n60-pro
netcore,n60-pro)
	# 这里的 mdio-bus 前缀代表直接读取交换机芯片上的 LED 状态
	ucidef_set_led_netdev "wanlink" "WANLINK" "mdio-bus:06:green:wan" "eth1" "link_10 link_100 link_1000 link_2500 tx rx"
	ucidef_set_led_netdev "lan-1" "LAN-1" "mdio-bus:05:green:lan" "lan1" "link_10 link_100 link_1000 link_2500 tx rx"
	ucidef_set_led_netdev "wan" "WAN" "blue:wan" "eth1" "link"
	;;
# 针对 netgear wax220
netgear,wax220)
	ucidef_set_led_netdev "eth0" "LAN" "green:lan" "eth0"
	;;
# 针对 netis nx31
netis,nx31)
	ucidef_set_led_netdev "wan" "wan" "blue:wan" "eth1" "link tx rx"
	;;
# 针对 openembed som7981 核心板
openembed,som7981)
	ucidef_set_led_netdev "lanact" "LANACT" "amber:lan" "eth1" "rx tx" # amber 代表琥珀色/黄色灯，仅数据收发时亮
	ucidef_set_led_netdev "lanlink" "LANLINK" "green:lan" "eth1" "link" # 仅链路连接时亮
	;;
# 针对 openwrt one 开发板
openwrt,one)
	ucidef_set_led_netdev "wanact" "WANACT" "mdio-bus:0f:green:wan" "eth0" "rx tx"
	ucidef_set_led_netdev "wanlink" "WANLINK" "mdio-bus:0f:amber:wan" "eth0" "link"
	ucidef_set_led_netdev "lanact" "LANACT" "green:lan" "eth1" "rx tx"
	ucidef_set_led_netdev "lanlink" "LANLINK" "amber:lan" "eth1" "link"
	;;
# 针对 routerich ax3000 及其 ubootmod 版本
routerich,ax3000|\
routerich,ax3000-ubootmod)
	ucidef_set_led_netdev "lan-1" "lan-1" "blue:lan-1" "lan1" "link tx rx"
	ucidef_set_led_netdev "lan-2" "lan-2" "blue:lan-2" "lan2" "link tx rx"
	ucidef_set_led_netdev "lan-3" "lan-3" "blue:lan-3" "lan3" "link tx rx"
	ucidef_set_led_netdev "wan" "wan" "blue:wan" "wan" "link tx rx"
	ucidef_set_led_netdev "wan-off" "wan-off" "red:wan" "wan" "link" # 额外的红色 WAN 灯，用于指示断开状态
	;;
# 针对 routerich ax3000-v1
routerich,ax3000-v1)
	ucidef_set_led_netdev "lan-1" "lan-1" "blue:lan-1" "lan1" "link tx rx"
	ucidef_set_led_netdev "lan-2" "lan-2" "blue:lan-2" "lan2" "link tx rx"
	ucidef_set_led_netdev "lan-3" "lan-3" "blue:lan-3" "lan3" "link tx rx"
	ucidef_set_led_netdev "wan" "wan" "blue:wan" "eth1" "link tx rx"
	ucidef_set_led_netdev "wan-off" "wan-off" "red:wan" "eth1" "link"
	;;
# 针对 smartrg sdg-8733 / sdg-8734
smartrg,sdg-8733|\
smartrg,sdg-8734)
	# 这些设备支持多速率指示灯（不同网速亮不同颜色的灯）
	ucidef_set_led_netdev "lan-1-green" "LAN1" "mdio-bus:08:green:lan" "lan1" "link_2500 link_5000" # 2.5G/5G 亮绿灯
	ucidef_set_led_netdev "lan-1-orange" "LAN1" "mdio-bus:08:orange:lan" "lan1" "link_100 link_1000" # 100M/1G 亮橙灯
	ucidef_set_led_netdev "lan-1-white" "LAN1" "mdio-bus:08:white:lan" "lan1" "link_10000" # 10G 亮白灯
	ucidef_set_led_netdev "lan-2-green" "LAN2" "mt7530-0:01:green:lan" "lan2" "link_1000"
	ucidef_set_led_netdev "lan-2-amber" "LAN2" "mt7530-0:01:amber:lan" "lan2" "link_100 link_10"
	ucidef_set_led_netdev "lan-3-green" "LAN3" "mt7530-0:02:green:lan" "lan3" "link_1000"
	ucidef_set_led_netdev "lan-3-amber" "LAN3" "mt7530-0:02:amber:lan" "lan3" "link_100 link_10"
	ucidef_set_led_netdev "lan-4-green" "LAN4" "mt7530-0:03:green:lan" "lan4" "link_1000"
	ucidef_set_led_netdev "lan-4-amber" "LAN4" "mt7530-0:03:amber:lan" "lan4" "link_100 link_10"
	ucidef_set_led_netdev "wan-green" "WAN" "mdio-bus:00:green:wan" "wan" "link_2500 link_5000"
	ucidef_set_led_netdev "wan-orange" "WAN" "mdio-bus:00:orange:wan" "wan" "link_100 link_1000"
	ucidef_set_led_netdev "wan-white" "WAN" "mdio-bus:00:white:wan" "wan" "link_10000"
	;;
# 针对 smartrg sdg-8733a
smartrg,sdg-8733a)
	ucidef_set_led_netdev "lan-green-act" "LAN" "mdio-bus:0f:green:lan" "lan" "link_2500"
	ucidef_set_led_netdev "lan-amber" "LAN" "amber:lan" "lan" "link_100"
	ucidef_set_led_netdev "lan-green" "LAN" "green:lan" "lan" "link_1000"
	ucidef_set_led_netdev "wan-green" "WAN" "mdio-bus:08:green:wan" "wan" "link_2500 link_5000"
	ucidef_set_led_netdev "wan-orange" "WAN" "mdio-bus:08:orange:wan" "wan" "link_100 link_1000"
	ucidef_set_led_netdev "wan-white" "WAN" "mdio-bus:08:white:wan" "wan" "link_10000"
	;;
# 针对 tplink re6000xd
tplink,re6000xd)
	ucidef_set_led_netdev "lan-1" "lan-1" "blue:lan-0" "lan1" "link tx rx"
	ucidef_set_led_netdev "lan-2" "lan-2" "blue:lan-1" "lan2" "link tx rx"
	ucidef_set_led_netdev "eth1" "lan-3" "blue:lan-2" "eth1" "link tx rx"
	;;
# 针对 wavlink wl-wn586x3
wavlink,wl-wn586x3)
	ucidef_set_led_netdev "lan-1" "lan-1" "blue:lan-1" "lan1" "link tx rx"
	ucidef_set_led_netdev "lan-2" "lan-2" "blue:lan-2" "lan2" "link tx rx"
	ucidef_set_led_netdev "wan" "wan" "blue:wan" "eth1" "link tx rx"
	;;
# 针对小米 wr30u 的官方固件及 ubootmod 版本
xiaomi,mi-router-wr30u-stock|\
xiaomi,mi-router-wr30u-ubootmod)
	ucidef_set_led_netdev "wan" "wan" "blue:wan" "
